# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ../lib/bencode.h \
    ../lib/blobkey.h
SOURCES += ../lib/bencode.cpp \
    ../lib/blobkey.cpp
