#ifndef NEOSCRIPTTOOLS_GLOBAL_H
#define NEOSCRIPTTOOLS_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef NEOSCRIPTTOOLS_LIB
# define NEOSCRIPTTOOLS_EXPORT Q_DECL_EXPORT
#else
# define NEOSCRIPTTOOLS_EXPORT Q_DECL_IMPORT
#endif

#endif // NEOSCRIPTTOOLS_GLOBAL_H
