# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------


HEADERS += ./mediaplayer_global.h \
    ./player.h \
    ./playercontrols.h \
    ./videowidget.h
SOURCES += ./player.cpp \
    ./playercontrols.cpp \
    ./videowidget.cpp
