# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ./qtping.h \
    ./qtping_global.h \
    ./qtpinger.h \
    ./qtpinger_unix.h
SOURCES += ./qtping.cpp \
    ./qtpinger_unix.cpp
