# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ../src/qftp/qftp_p.h \
    ../src/qftp/qurlinfo.h \
    ./qtftp_global.h \
    ../src/qftp/qftp.h
SOURCES += ../src/qftp/qftp.cpp \
    ../src/qftp/qurlinfo.cpp
